name: karmm_ios_voip_kit
description: One-to-one video call using CallKit and PushKit with flutter ios app.
version: 0.0.1
homepage: https://github.com/arv-gts-020/karmm_ios_voip_kit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: netkeepingblog.flutter_ios_voip_kit
        pluginClass: FlutterIOSVoIPKitPlugin
      ios:
        pluginClass: FlutterIOSVoIPKitPlugin
